### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [SPTecPrzemek/projekt105#1]
button 4 po kliknieciu zwraca `undefined`. Alternatywa z prototypem jest dobrze zrobiona, ale zapomniales o jednym szczegole, ktory jest wlasnie istota tego zadania

**Comment by SPTecPrzemek** [comment]
wszystko ok :) tak mialo byc :) sprawdzalem istote tego zadania, czyli brak self :) tylko przed wrzuceniem na gita zapomnialem usunac albo dac prawidlowy komentarz :)
